// <auto-generated />
using System;
using EleicaoCipa.Infraestrutura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EleicaoCipa.Infraestrutura.Data.Migrations
{
    [DbContext(typeof(EleicaoContext))]
    partial class EleicaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EleicaoCipa.Dominio.Model.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_inscricao");

                    b.Property<string>("Discurso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EleicaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EleicaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("EleicaoCipa.Dominio.Model.Eleicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("data_inicio");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("Eleicoes");
                });

            modelBuilder.Entity("EleicaoCipa.Dominio.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EleicaoCipa.Dominio.Model.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("data_voto")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EleicaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EleicaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("EleicaoCipa.Dominio.Model.Candidato", b =>
                {
                    b.HasOne("EleicaoCipa.Dominio.Model.Eleicao", "Eleicao")
                        .WithMany("Candidatos")
                        .HasForeignKey("EleicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EleicaoCipa.Dominio.Model.Usuario", "Usuario")
                        .WithMany("Candidatos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleicao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EleicaoCipa.Dominio.Model.Voto", b =>
                {
                    b.HasOne("EleicaoCipa.Dominio.Model.Candidato", "Candidato")
                        .WithMany("Votos")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EleicaoCipa.Dominio.Model.Eleicao", "Eleicao")
                        .WithMany("Votos")
                        .HasForeignKey("EleicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EleicaoCipa.Dominio.Model.Usuario", "Usuario")
                        .WithMany("Votos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Eleicao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EleicaoCipa.Dominio.Model.Candidato", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("EleicaoCipa.Dominio.Model.Eleicao", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("EleicaoCipa.Dominio.Model.Usuario", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
